account = "13350865639"
password = "yun13350865639"

"""上证成指"""
jq_stock_sse_code = "000001.XSHG"
jq_stock_sse_code_name = "SSE"
"""深证成指"""
jq_stock_szcz_code = "399001.XSHE"
jq_stock_szcz_code_name = "SZCZ"
"""创业板指"""
jq_stock_cybz_code = "399006.XSHE"
jq_stock_cybz_code_name = "CYBZ"

"""纳斯达克"""
jq_stock_ixic_code = "IXIC"
jq_stock_ixic_code_name = "IXIC"
"""道琼斯"""
jq_stock_dji_code = "DJI"
jq_stock_dji_code_name = "DJI"
"""标普500"""
jq_stock_inx_code = "INX"
jq_stock_inx_code_name = "INX"