"""获取投资者列表"""
snow_ball_position_url = "https://xueqiu.com/cubes/discover/rank/cube/list.json?category=14&page=1&count="
"""雪球首页 当做登陆 会话使用"""
snow_ball_main_url = "https://xueqiu.com/"
"""获取指定投资者仓位"""
snow_ball_investor_url = "https://xueqiu.com/cubes/rebalancing/show_origin.json?rb_id="